---
- hosts: localhost
  connection: local
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: All IPv4 Address
    debug: msg={{ansible_all_ipv4_addresses}}
  - name: Default IPv4 address
    debug: msg={{ansible_default_ipv4.address}}
    
- hosts: localhost
  connection: local
  vars_files:
    - "group_vars/macos.yml"
  roles:
    - role: "harness"
