---
- block: 
  - name: Run Drone Runner
    shell: |
      docker run --detach \
      --volume=/var/run/docker.sock:/var/run/docker.sock \
      --env=DRONE_RPC_PROTO=http \
      --env=DRONE_RPC_HOST={{ drone_server_ip }} \
      --env=DRONE_RPC_SECRET={{ drone_secret }} \
      --env=DRONE_RUNNER_CAPACITY=2 \
      --env=DRONE_RUNNER_NAME=my-first-runner \
      --publish=3000:3000 \
      --restart=always \
      --name=runner \
      drone/drone-runner-docker:1
    register: runner
    failed_when: runner.rc != 0
  
  - name: Show output of runner launch
    debug:
      msg: 'Drone Runner output: {{ runner.stdout }}'