---
- block: 
  - name: Pull Drone Runner Image
    shell: |
      docker pull drone/drone-runner-docker:1

  - name: Run Drone Runner
    shell: |
      docker run --detach \
      --volume=/var/run/docker.sock:/var/run/docker.sock \
      --env=DRONE_RPC_PROTO=http \
      --env=DRONE_RPC_HOST={{ ansible_default_ipv4.address }} \
      --env=DRONE_RPC_SECRET={{ shared_secret }} \
      --env=DRONE_RUNNER_CAPACITY=2 \
      --env=DRONE_RUNNER_NAME=my-first-runner \
      --publish=3000:3000 \
      --restart=always \
      --name=runner \
      drone/drone-runner-docker:1
    register: runner
    failed_when: runner.rc != 0
      
  - name: Show output of runner launch
    debug:
      msg: 'Drone Runner output: {{ runner.stdout }}'