---
- block: 
  - name: Downloading Harness Delegate
    get_url:
      url: "{{ cdcg_delegate_url | trim }}"
      dest: "{{ harness_dir }}/harness-delegate-docker.tar.gz"

  - name: Unarchive Harness Delegate
    shell: "cd {{ harness_dir }} && tar -xvzf {{ harness_dir }}/harness-delegate-docker.tar.gz"
  
  - name: Pull Harness Delegate Docker Image
    shell: |
      docker pull harness/delegate:latest

  - name: Run Harness Delegate
    shell: "{{ harness_dir }}/harness-delegate-docker/launch-harness-delegate.sh"
    register: delegate
    failed_when: delegate.rc != 0
  
  - name: Show output of delegate launch
    debug:
      msg: 'Delegate output: {{ delegate.stdout }}'
