---
- block: 
  - name: Downloading Harness Delegate
    unarchive:
      src: "{{ cdcg_delegate_url | trim }}"
      dest: "/home/alejandro.talamantes"
      mode: 0755
      remote_src: yes
  
  - name: Run Harness Delegate
    shell: "/home/alejandro.talamantes/harness-delegate-docker/launch-harness-delegate.sh"
    register: delegate
    failed_when: delegate.rc != 0
  
  - name: Show output of delegate launch
    debug:
      msg: 'Delegate output: {{ delegate.stdout }}'